### ISSUE TITLE
There is no team project named 'TestJiraToTFS' in source control

### ISSUE THREAD

**Issue by vinotheswaramoorthy** [KilskyreMan/JiraToTfs#12]
![jiratotfs2](https://cloud.githubusercontent.com/assets/8022604/18461585/d56676f8-7998-11e6-914d-880cc3d67f1f.png)

![jiratotfs](https://cloud.githubusercontent.com/assets/8022604/18461586/d5669e8a-7998-11e6-86ab-584ce3d8f9b3.png)

After choosing team projects in 'Connect to Team Foundation Server' window, "There is no team project named 'TestJiraToTFS' in source control" error comes due to not finding the source in the given TFS server. but it lists the projects in that TFS server. How to solve this issue?

**Comment by mevoronin** [comment]
I have the same error.

**Comment by Woodkie** [comment]
I was able to reproduce this error when attaching to a TFS project that was set for Git as it's primary source control repository. When connecting to a TFSVC project I don't get the error.  I get other ones....

**Comment by KilskyreMan** [comment]
Hi Guys,

I have some time tomorrow to have a look and see what the problem is. I'll get back if I have any answers or need further information.

Cheers - Ian.

**Comment by KilskyreMan** [comment]
Which version of TFS were you using? it will help narrow the problem.

**Comment by KilskyreMan** [comment]
@Kaaikaula - you mentioned you were getting other errors in your comment above. Can you describe the issues you were getting (as mentioned above, all information welcome, it will help narrow the problem).

**Comment by Zay** [comment]
I am getting the same error as mentioned. I thought it might be a problem because our team project has spaces, until @Kaaikaula mentioned Git.
I'm also using Git and getting the same error on our cloud based (visualstudio.com) TFS. I can select the project on the TFS selection screen, but cannot connect to it from the tool.

**Comment by KilskyreMan** [comment]
@Zay thanks for that. I'm able to replicate the problem and am currently working on a fix.

**Comment by KilskyreMan** [comment]
Hi Guys, This issue should now be addressed. See version 1.1.
